DEFAULT_MAP_WIDTH = 30
DEFAULT_MAP_HEIGHT = 30
DEFAULT_NUM_STATIONS = 10
DEFAULT_NUM_LINES = 5
DEFAULT_NUM_HUBS = 1
DEFAULT_DEBUG_MODE = False

TOP_LEFT_CORNER = "┏"
TOP_RIGHT_CORNER = "┓"
BOTTOM_LEFT_CORNER = "┗"
BOTTOM_RIGHT_CORNER = "┛"
VERTICAL_PIPE = "┃"
HORIZONTAL_PIPE = "━"